--script do banco
CREATE TABLE PARTNER (
 PARTNERCODE INTEGER NOT NULL,
 NAME VARCHAR(30) NOT NULL,
 PHONE INTEGER NOT NULL,
 EMAIL VARCHAR(30) NOT NULL,
 RATING INTEGER NOT NULL,
 PRIMARY KEY (PARTNERCODE)
);

